#!/bin/bash
##################################################################################################
# Explanation:
# * This code calculates partial volume corrected SUVs (NOT RESCALED) of flipped PET files 
#   based on coreg param and gtmseg

export FREESURFER_HOME=/usr/local/freesurfer_6/freesurfer
FSFOLDER_DIR=/DATA/IMAGE_DAY/FS/3_fsresults_gtmseg
PET_INPUT_FOLDER=/DATA/IMAGE_DAY/PET/1_2_pet_nii_flip
PARAM_INPUT_FOLDER=/DATA/IMAGE_DAY/PET/2_mri-pet_coreg/param
GTMPVC_OUTPUT_FOLDER=/DATA/IMAGE_DAY/PET/3_gtmpvc

pettype="_apet" #<- "_apet" or "_fpet"
SUBJECTS=( 10005259 10009989 )

PET_DATES=(200514 190227 )
MRI_DATES=(200514 180124 )
##################################################################################################

source $FREESURFER_HOME/SetUpFreeSurfer.sh
SUBJECTS_DIR=$FSFOLDER_DIR

for idx in ${!SUBJECTS[*]}

	do
	subj="r"${SUBJECTS[$idx]}"_"${MRI_DATES[$idx]}
	subj_pet=${SUBJECTS[$idx]}"_"${PET_DATES[$idx]}$pettype	

	mri_gtmpvc --i $PET_INPUT_FOLDER/"flip_"$subj_pet.nii \
		   --reg $PARAM_INPUT_FOLDER/$subj_pet"_coreg2M"${MRI_DATES[$idx]}.reg.lta   \
		   --seg $SUBJECTS_DIR/$subj/mri/gtmseg.mgz \
		   --psf 8 --default-seg-merge --auto-mask PSF .01 \
		   --o $GTMPVC_OUTPUT_FOLDER/gtmpvc_$subj_pet"_coreg2M"${MRI_DATES[$idx]}.output \
		   --no-rescale
done
