function [orig_aseg] = import_aseg_csv(filename)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /media/subin/DATA/0_FS_reorder_test/allscrbl_subcortvol.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/03/31 21:57:32

%% Initialize variables.
% filename = '/media/subin/DATA/0_FS_reorder_test/allscrbl_subcortvol.csv';
delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
%	column56: double (%f)
%   column57: double (%f)
%	column58: double (%f)
%   column59: double (%f)
%	column60: double (%f)
%   column61: double (%f)
%	column62: double (%f)
%   column63: double (%f)
%	column64: double (%f)
%   column65: double (%f)
%	column66: double (%f)
%   column67: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
orig_aseg = table(dataArray{1:end-1}, 'VariableNames', {'Measurevolume','LeftLateralVentricle','LeftInfLatVent','LeftCerebellumWhiteMatter','LeftCerebellumCortex','LeftThalamusProper','LeftCaudate','LeftPutamen','LeftPallidum','rdVentricle','thVentricle','BrainStem','LeftHippocampus','LeftAmygdala','CSF','LeftAccumbensarea','LeftVentralDC','Leftvessel','Leftchoroidplexus','RightLateralVentricle','RightInfLatVent','RightCerebellumWhiteMatter','RightCerebellumCortex','RightThalamusProper','RightCaudate','RightPutamen','RightPallidum','RightHippocampus','RightAmygdala','RightAccumbensarea','RightVentralDC','Rightvessel','Rightchoroidplexus','thVentricle1','WMhypointensities','LeftWMhypointensities','RightWMhypointensities','nonWMhypointensities','LeftnonWMhypointensities','RightnonWMhypointensities','OpticChiasm','CC_Posterior','CC_Mid_Posterior','CC_Central','CC_Mid_Anterior','CC_Anterior','BrainSegVol','BrainSegVolNotVent','BrainSegVolNotVentSurf','lhCortexVol','rhCortexVol','CortexVol','lhCorticalWhiteMatterVol','rhCorticalWhiteMatterVol','CorticalWhiteMatterVol','SubCortGrayVol','TotalGrayVol','SupraTentorialVol','SupraTentorialVolNotVent','SupraTentorialVolNotVentVox','MaskVol','BrainSegVoltoeTIV','MaskVoltoeTIV','lhSurfaceHoles','rhSurfaceHoles','SurfaceHoles','EstimatedTotalIntraCranialVol'});

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;