#!/bin/bash
export FREESURFER_HOME=/usr/local/freesurfer_6/freesurfer
FSFOLDER_DIR=/DATA/IMAGE_DAY/FS/2_fsresults_gtmseg
PET_INPUT_FOLDER=/DATA/IMAGE_DAY/PET/1_2_pet_nii_flip
PARAM_OUTPUT_FOLDER=/DATA/IMAGE_DAY/PET/2_mri-pet_coreg/param
COREGPET_OUTPUT_FOLDER=/DATA/IMAGE_DAY/PET/2_mri-pet_coreg/coreg_pet

pettype="_apet" #<- "_apet" or "_fpet"
SUBJECTS=( 10005259 10009989 )

PET_DATES=(200514 190227 )
MRI_DATES=(200514 180124 )

##################################################################################################

source $FREESURFER_HOME/SetUpFreeSurfer.sh
SUBJECTS_DIR=$FSFOLDER_DIR

#1. MRI-PET coregistration
#for idx in ${!SUBJECTS[*]}

	#do
	#subj="r"${SUBJECTS[$idx]}"_"${MRI_DATES[$idx]}
	#subj_pet=${SUBJECTS[$idx]}"_"${PET_DATES[$idx]}$pettype	

	#mri_coreg --s $subj \
	#	  --mov $PET_INPUT_FOLDER/"flip_"$subj_pet.nii \
	#	  --reg $PARAM_OUTPUT_FOLDER/$subj_pet"_coreg2M"${MRI_DATES[$idx]}.reg.lta 

	#mri_vol2vol --mov $PET_INPUT_FOLDER/"flip_"$subj_pet.nii \
	#	    --targ $SUBJECTS_DIR/$subj/mri/brainmask.mgz \
	#	    --reg $PARAM_OUTPUT_FOLDER/$subj_pet"_coreg2M"${MRI_DATES[$idx]}.reg.lta \
	#	    --o $COREGPET_OUTPUT_FOLDER/$subj_pet"_coreg2M"${MRI_DATES[$idx]}.nii		  
#done



#2. Check MRI-PET coregistration
for idx in ${!SUBJECTS[*]}

	do
	subj="r"${SUBJECTS[$idx]}"_"${MRI_DATES[$idx]}
	subj_pet=${SUBJECTS[$idx]}"_"${PET_DATES[$idx]}$pettype	

	cd $PET_INPUT_FOLDER
	tkregisterfv --mov $PET_INPUT_FOLDER/"flip_"$subj_pet.nii \
		     --targ $SUBJECTS_DIR/$subj/mri/brainmask.mgz \
		     --reg $PARAM_OUTPUT_FOLDER/$subj_pet"_coreg2M"${MRI_DATES[$idx]}.reg.lta \
		     --s /$subj \
		     --surfs 		  
done





