#!/bin/bash
# * This code uploads the outputs from the current batch of subjects to Server.

FSFOLDER_DIR=/DATA/IMAGE_DAY/FS/3_fsresults_gtmseg
PARAM_FOLDER=/DATA/IMAGE_DAY/PET/3_mri-pet_coreg/param
COREGPET_FOLDER=/DATA/IMAGE_DAY/PET/3_mri-pet_coreg/coreg_pet
GTMPVC_FOLDER=/DATA/IMAGE_DAY/PET/4_gtmpvc

SERVER_PARAM_FOLDER=/media/fsdb2_mnt/ps_snubh/Amyloid-PET/5_1_MRICOREG/PARAM
SERVER_COREGPET_FOLDER=/media/fsdb2_mnt/ps_snubh/Amyloid-PET/5_1_MRICOREG/COREG_PET
SERVER_GTMPVC_FOLDER=/media/fsdb2_mnt/ps_snubh/Amyloid-PET/5_2_GTMPVC

pettype="_apet" #<- "_apet" or "_fpet"


cp $PARAM_FOLDER/*.reg.lta $SERVER_PARAM_FOLDER
cp $COREGPET_FOLDER/*.nii $SERVER_COREGPET_FOLDER
cp -R $GTMPVC_FOLDER/*.output $SERVER_GTMPVC_FOLDER


