#!/bin/bash
#had to cd /usr/local/freesurfer_6/freesurfer/bin; sudo chown 8481:1590 gtmstats2table before usage
# and maybe chmod 770 gtmstats2table
# even after that, i think i had to run this code with sudo. anyways, it works :)
# https://mail.nmr.mgh.harvard.edu/pipermail//freesurfer/2017-July/052671.html 

export FREESURFER_HOME=/usr/local/freesurfer_6/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

GTMPVC_OUTPUT_FOLDER=/DATA/IMAGE_DAY/PET/4_gtmpvc #/media/fsdb2_mnt/ps_snubh/Amyloid-PET/4_GTMPVC
GTMPVC_STATS_FOLDER=/media/fsdb2_mnt/ps_snubh/Amyloid-PET/6_GTMPVC_STATS
pettype="_apet" #<- "_apet" or "_fpet"

date="210208"

##############################################################################################3
source $FREESURFER_HOME/SetUpFreeSurfer.sh
FSFOLDER_DIR=/DATA/IMAGE_DAY/FS/3_fsresults_gtmseg
SUBJECTS_DIR=$FSFOLDER_DIR


cd $GTMPVC_OUTPUT_FOLDER
#1.
for subj_gtmpvcfolder in $(ls -1 ) 

	do

	echo $subj_gtmpvcfolder >> gtmpvclist$pettype"_"$date
done
	
	sudo chmod 770 gtmpvclist$pettype"_"$date
	sudo chown user:user gtmpvclist$pettype"_"$date
	sudo mv gtmpvclist$pettype"_"$date $GTMPVC_STATS_FOLDER

gtmstats2table --f $GTMPVC_STATS_FOLDER/gtmpvclist$pettype"_"$date \
			--o $GTMPVC_STATS_FOLDER/gtmstats$pettype"_"$date.csv
	

