function [orig_aparc_rh] = import_aparc_rh_csv(filename)
%% Import data from text file.

% Auto-generated by MATLAB on 2020/03/31 21:44:10

%% Initialize variables.
delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
orig_aparc_rh = table(dataArray{1:end-1}, 'VariableNames', {'rhaparcvolume','rh_bankssts_volume','rh_caudalanteriorcingulate_volume','rh_caudalmiddlefrontal_volume','rh_cuneus_volume','rh_entorhinal_volume','rh_fusiform_volume','rh_inferiorparietal_volume','rh_inferiortemporal_volume','rh_isthmuscingulate_volume','rh_lateraloccipital_volume','rh_lateralorbitofrontal_volume','rh_lingual_volume','rh_medialorbitofrontal_volume','rh_middletemporal_volume','rh_parahippocampal_volume','rh_paracentral_volume','rh_parsopercularis_volume','rh_parsorbitalis_volume','rh_parstriangularis_volume','rh_pericalcarine_volume','rh_postcentral_volume','rh_posteriorcingulate_volume','rh_precentral_volume','rh_precuneus_volume','rh_rostralanteriorcingulate_volume','rh_rostralmiddlefrontal_volume','rh_superiorfrontal_volume','rh_superiorparietal_volume','rh_superiortemporal_volume','rh_supramarginal_volume','rh_frontalpole_volume','rh_temporalpole_volume','rh_transversetemporal_volume','rh_insula_volume'});

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;