#!/bin/bash
##################################################################################################
# * This code does the following preprocessing steps for pet images:
#   1. Renames pet .hdr/img files to simpler name
#      (ex).'_Neuraceq+Reframe'-->'_apet'  (ex).'_3D_Brain'-->'_fpet')  
#   2. Converts renamed .hdr/img files to .nii 
#      We are using spm's function instead of FreeSurfer's mri_convert because 
#      mri_convert results in bad magic number errors).
#   3. Left-right flips the .nii files
#      Using spm's function results in having to left-right flip for good mri-coregistration later  
#
# * mscriptdir is where the 'Preprocess_PETimages_workflow.m' is located
# * tmp_dir is where the .hdr/img pet files are temporarily downloaded from Server for processing
# * nii_dir is where the .nii outputs will be created
# * flip_nii_dir is where the flipped .nii outputs will be created
# * pettype labels whether current pet files are amyloid pet or fdg pet
# * SUBJECTS is the collection of subjects to be run

mscriptdir=/media/ws2/DATA/IMAGE_DAY/PET/SCRIPTS
tmp_dir=/media/ws2/DATA/IMAGE_DAY/PET/0_pet_hdrimg
rename_hdrimg_dir=/media/ws2/DATA/IMAGE_DAY/PET/1_1_pet_hdrimg_renamed
nii_dir=/media/ws2/DATA/IMAGE_DAY/PET/1_2_pet_nii
flip_nii_dir=/media/ws2/DATA/IMAGE_DAY/PET/1_3_pet_nii_flip

pettype="_apet" #<- "_apet" or "_fpet"
SUBJECTS_PET=(10009989_190227 10037162_191211 10039803_170201 10049406_170722 10057135_180124 10060232_200601 10088913_161103 10121757_181119 10124059_180130 10124129_171129 10124578_191030 10132384_200909 10188394_181128 10193149_180129 10200186_170708 10221176_170603 10286623_180511 10292457_200619 10297111_200915 10299193_200811 10348158_170330 10352708_180509 10361430_201023 10384109_180331 10415623_191211 10431593_191203 10436839_170331 10462256_201012 10463538_170327 10483549_200703 10487611_200908 10495751_200819 10582554_200304 10606607_200410 10622630_170527 10626719_180907 10636350_170121 )
##################################################################################################

# 1. Rename files to simpler name:
for idx in ${!SUBJECTS_PET[*]}
	do
	cd $tmp_dir
	mv ${SUBJECTS_PET[$idx]}*.hdr $rename_hdrimg_dir/${SUBJECTS_PET[$idx]}$pettype.hdr
	mv ${SUBJECTS_PET[$idx]}*.img $rename_hdrimg_dir/${SUBJECTS_PET[$idx]}$pettype.img	
done

# 2. Use matlab script to nii-transform and flip:
matlab -nodesktop -nosplash -nojvm -r "cd('$mscriptdir');Preprocess_PETimages_workflow('$rename_hdrimg_dir', '$pettype', '$nii_dir', '$flip_nii_dir');exit" |tail -n +14






