#!/bin/bash

export FREESURFER_HOME=/usr/local/freesurfer_6/freesurfer

FSRESULTS_ALL_DIR=/media/fsdb1_mnt/fs_snubh/2_FSRESULTS_V6_ALL

OUTPUT_DIR_WMPARC=/media/fsdb1_mnt/fs_snubh/4_FS_MASKS/WMPARC
OUTPUT_DIR_DESTRIEUX=/media/fsdb1_mnt/fs_snubh/4_FS_MASKS/DESTRIEUX
OUTPUT_DIR_DKT=/media/fsdb1_mnt/fs_snubh/4_FS_MASKS/DKT

T1_ISO_DIR=/media/fsdb1_mnt/fs_snubh/1_T1_isonii

SUBJECT_FOLDERS=()

###################################################################################
source $FREESURFER_HOME/SetUpFreeSurfer.sh
SUBJECTS_DIR=/media/fsdb1_mnt/fs_snubh/2_FSRESULTS_V6_ALL

for idx in ${!SUBJECT_FOLDERS[*]}

	do

	subj=${SUBJECT_FOLDERS[$idx]}

	cd $FSRESULTS_ALL_DIR/"r"$subj/mri
	
	mri_convert -i wmparc.mgz -o $OUTPUT_DIR_WMPARC/"r"$subj"_wmparc".nii \
			-rt nearest -rl $T1_ISO_DIR/"r"$subj"_T1".nii

	mri_convert -i aparc.a2009s+aseg.mgz -o $OUTPUT_DIR_DESTRIEUX/"r"$subj"_a2009s".nii \
			-rt nearest -rl $T1_ISO_DIR/"r"$subj"_T1".nii

	mri_convert -i aparc.DKTatlas+aseg.mgz -o $OUTPUT_DIR_DKT/"r"$subj"_dkt".nii \
			-rt nearest -rl $T1_ISO_DIR/"r"$subj"_T1".nii

done




