#!/bin/bash
export FREESURFER_HOME=/usr/local/freesurfer_53/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

#Specify folder to download files from server
DOWNLOADFOLDER=/media/ws1/DATA/NIPA2018/SNUBH_DATA_Year2/190807_NEW_for_700-700SET_NOINFO/0_nii


#Specify filenames (old and new): #)
HOSPDATE_array=(22047232_130621 10969625_130627 11718039_130708 22084736_130711 21962136_130627 21660935_130704 17067025_130713 18798586_130621 22083625_130614 22005618_130701 13102205_130628 10820403_130614 10465471_130618 ) 


CERADDATE_array=(BD7158_130621 BD7237_130627 BD7253_130708 BD7260_130711 BD7271_130627 BD7277_130704 BDA0033_130713 BDE0212_130621 BDE0216_130614 BDE1096_130701 BDE1099_130628 GC0485_130614 XX0045_130618 ) 



#Copy T1/FLAIR hdr/img files from server
for idx in ${!HOSPDATE_array[*]}
	do
	cd /media/mri_dicom_mnt/*/${HOSPDATE_array[$idx]}
		#-FOR T1 ONLY:	
		cp ${HOSPDATE_array[$idx]}*"T1"*.hdr $DOWNLOADFOLDER
		cp ${HOSPDATE_array[$idx]}*"T1"*.img $DOWNLOADFOLDER
		#-FOR FLAIR ONLY:	
		#cp ${HOSPDATE_array[$idx]}*"FLAIR"* $DOWNLOADFOLDER
done

#Reslice to isovoxel, convert to nii, and rename files (replace hospital number with cerad number):
for idx in ${!HOSPDATE_array[*]}
	do
	cd $DOWNLOADFOLDER
		#-FOR T1 ONLY:
#		mri_convert -vs 1 1 1 -it nifti1 -ot nii -i ${HOSPDATE_array[$idx]}*.hdr -o "r"${CERADDATE_array[$idx]}.nii 
		mri_convert -it nifti1 -ot nii -i ${HOSPDATE_array[$idx]}*.hdr -o ${CERADDATE_array[$idx]}.nii 
		#-FOR FLAIR ONLY:
		#-FOR FLAIR, DELETE ANY SAG_FLAIR FILES FIRST !!!!!!!!*************	
		#mv ${HOSPDATE_array[$idx]}*.hdr ${CERADDATE_array[$idx]}"_FLAIR".hdr 
		#mv ${HOSPDATE_array[$idx]}*.img ${CERADDATE_array[$idx]}"_FLAIR".img 
done



